# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8019803ae9749657f47793ff3ca3f58fb9fb638dc200b2c8a056da64aa6b5454726e1ea942d5864f6e6715813363215872c7853f78c724d5bd3dc8ec3aa5322b

test:
  secret_key_base: 94f88becd313ad8876664d3d6f3e6b0a945fc83f9b6b021daf2daa3e133f2300c7cadceadd59c04f84ec156b9f24e7cd746b38db7403e8226e89628731942efe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
